const spaceTopics = [
  "The Moon",
  "Black Holes",
  "Exoplanets",
  "Comets",
  "Mars Rovers",
  "The Sun",
  "Asteroids",
  "Nebulae",
  "Galaxies",
  "Supernovae",
  "Dark Matter",
  "Dark Energy",
  "Pulsars",
  "Quasars",
  "Cosmic Microwave Background",
  "Space Telescopes",
  "International Space Station",
  "Gravity Waves",
  "Planetary Rings",
  "Meteor Showers",
  "Space Probes",
  "Solar Flares",
  "Red Dwarfs",
  "White Dwarfs",
  "Neutron Stars",
  "Gamma Ray Bursts",
  "Space Colonization",
  "Terraforming",
  "Space Elevators",
  "Space Debris",
  "Solar Wind",
  "Magnetospheres",
  "Cosmic Rays",
  "Space Tourism",
  "Rocket Propulsion",
  "Lunar Bases",
  "Mars Colonies",
  "Space Mining",
  "Astrobiology",
  "Space Weather",
  "Exomoons",
  "SpaceX",
  "Blue Origin",
  "Voyager Missions",
  "Hubble Space Telescope",
  "James Webb Space Telescope",
  "SETI",
  "Orbital Mechanics",
  "Zero Gravity",
  "Space Stations",
  "Telescope Arrays",
  "Gravitational Lensing",
  "Solar System Formation",
  "Big Bang",
  "Multiverse Theory",
  "Cosmology",
  "Dark Energy Survey",
  "Astrophysics",
  "Infrared Astronomy",
  "Radio Astronomy",
  "X-ray Astronomy",
  "Space Farming",
  "Space Robots",
  "Artificial Gravity",
  "Space Habitats",
  "Space Law",
  "Exoplanet Atmospheres",
  "Space Elevators",
  "Asteroid Redirect Mission",
  "Planetary Nebula",
  "Brown Dwarfs",
  "Solar Eclipses",
  "Lunar Eclipses",
  "Space Medicine",
  "Space Farming",
  "Orbital Debris",
  "Space Radiation",
  "Deep Space Network",
  "Interstellar Travel",
  "Space Navigation",
  "Space Colonies",
  "Space Elevators",
  "Space Launch Systems",
  "Space Shuttle",
  "Spacecraft Design",
  "Solar Dynamics Observatory",
  "Mars Sample Return",
  "Titan",
  "Europa",
  "Enceladus",
  "Kuiper Belt",
  "Oort Cloud",
  "Interplanetary Dust",
  "Cosmic Inflation",
  "Space-time",
  "Hawking Radiation",
  "Event Horizon",
  "Solar Cycle",
  "Planet Nine",
  "Lagrange Points",
  "Space-Based Solar Power",
  "Space Traffic Management"
];

export default spaceTopics;
